// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzBXv0zLgZWKbGsGE1SX_pv8E-Mdkq_38',
    appId: '1:738507391426:web:15b420615b6e2794b6965b',
    messagingSenderId: '738507391426',
    projectId: 'travel-wallet-app-747fe',
    authDomain: 'travel-wallet-app-747fe.firebaseapp.com',
    storageBucket: 'travel-wallet-app-747fe.firebasestorage.app',
    measurementId: 'G-HL9MRK8Y5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1bxGodiHip3RH4BT38AM5OVqw9iaOsA',
    appId: '1:738507391426:android:e19b3724cece8fdcb6965b',
    messagingSenderId: '738507391426',
    projectId: 'travel-wallet-app-747fe',
    storageBucket: 'travel-wallet-app-747fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn3eu9E9cIde14lE9bbuz-pGtOz1qLTok',
    appId: '1:738507391426:ios:ca959025fd98a5e5b6965b',
    messagingSenderId: '738507391426',
    projectId: 'travel-wallet-app-747fe',
    storageBucket: 'travel-wallet-app-747fe.firebasestorage.app',
    iosBundleId: 'com.bogdan.travelWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn3eu9E9cIde14lE9bbuz-pGtOz1qLTok',
    appId: '1:738507391426:ios:ca959025fd98a5e5b6965b',
    messagingSenderId: '738507391426',
    projectId: 'travel-wallet-app-747fe',
    storageBucket: 'travel-wallet-app-747fe.firebasestorage.app',
    iosBundleId: 'com.bogdan.travelWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzBXv0zLgZWKbGsGE1SX_pv8E-Mdkq_38',
    appId: '1:738507391426:web:e75097fe47dcab85b6965b',
    messagingSenderId: '738507391426',
    projectId: 'travel-wallet-app-747fe',
    authDomain: 'travel-wallet-app-747fe.firebaseapp.com',
    storageBucket: 'travel-wallet-app-747fe.firebasestorage.app',
    measurementId: 'G-0NBVS1P8D9',
  );
}
